### PR TITLE
pipeline: add helper shwrap() function

### PR DESCRIPTION
**Pull request by jlebon**
Add a helper to execute shell commands in a consistent environment with
the traditional `set -xeuo pipefail` and always starting in the `/srv`
dir. I initially played with `workingDir: /srv`, but the Kubernetes
plugin tries to be smart and interprets it as a mountpoint to mount into
the container. Which we don't want here since we already have an `/srv`
mountpoint.

I also removed the `| tee` since I don't think it's helping. I think the
issue there is that the `rpm-ostree` running inside supermin thinks it's
got a tty, so we'd have to hack this directly in the init script.

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: #20

**Comment by dustymabe** [comment]
> I also removed the `| tee` since I don't think it's helping. I think the
> issue there is that the `rpm-ostree` running inside supermin thinks it's
> got a tty

I just ran coreos-assembler (after executing `shell` to get into the container) redirecting all output to a file (i.e. no tty):

```
[coreos-assembler]$ /usr/bin/coreos-assembler build &> /tmp/file.txt
```

I see this in the output when I open the file in `vi`:

```
⠁ Importing rpm-md   0% [░░░░░░░░░░░░░░░░░░░░] (0s) ^M
^[[1A^M^[[2K^[[1B^[[1A⠙ Importing rpm-md  25% [██████░░░░░░░░░░░░░░] (3s) ^M
^[[1A^M^[[2K^[[1B^[[1A⠒ Importing rpm-md  50% [███████████░░░░░░░░░] (2s) ^M
^[[1A^M^[[2K^[[1B^[[1A⠂ Importing rpm-md  75% [████████████████░░░░] (1s) ^M
^[[1A^M^[[2K^[[1B^[[1AImporting rpm-md... done^M
```

should I open an upstream issue?

**Comment by dustymabe** [comment]
> I initially played with `workingDir: /srv`, but the Kubernetes
> plugin tries to be smart and interprets it as a mountpoint to mount into
> the container. Which we don't want here since we already have an `/srv`
> mountpoint.

yeah I hit that too when I was first playing around with this :(

**Comment by jlebon** [comment]
> should I open an upstream issue?

Sure, yeah. It's minor, though it shouldn't be too hard to fix.

**Comment by jlebon** [comment]
Rebased!

**Comment by dustymabe** [comment]
> > should I open an upstream issue?
> 
> Sure, yeah. It's minor, though it shouldn't be too hard to fix.

will do here in a minute

**Comment by dustymabe** [comment]
This LGTM

**Comment by dustymabe** [comment]
> > > should I open an upstream issue?
> > 
> > 
> > Sure, yeah. It's minor, though it shouldn't be too hard to fix.
> 
> will do here in a minute

opened upstream: https://github.com/projectatomic/rpm-ostree/issues/1689

**Pull request merged**
